sudo: required
services:
  - docker

before_install:
  - docker build -t saint/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true saint/react-test npm test

after_success:
  - docker build -t saint/multi-client ./client
  - docker build -t saint/multi-nginx ./nginx
  - docker build -t saint/multi-server ./server
  - docker build -t saint/multi-worker ./worker
# Log in to the docker CLI
# - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
# Take those images and push them to docker hub
# - docker push saint/multi-client
# - docker push saint/multi-nginx
# - docker push saint/multi-server
# - docker push saint/multi-worker   
